Repository johannes-kk/cs205_final_project, pull requests merged in 2020-05, with the labels that each got.

#38 Adding features to basic tree structure.
  src/datasets.cpp
  src/datasets.hpp
  src/decision_tree.cpp
  src/decision_tree.hpp
  src/test_datasets.cpp
  src/test_decision_tree.cpp
  src/test_tree.cpp
  src/test_tree_node.cpp
  src/tree.cpp
  src/tree.hpp
  src/tree_node.cpp
  src/tree_node.hpp
Labels: algorithm, enhancement

#42 Implement DataFrame class.
  src/datasets.cpp
  src/datasets.hpp
  src/test_datasets.cpp
Labels: enhancement, helpers

#47 Fix cross entropy.
  src/losses.cpp
  src/losses.hpp
  src/test_losses.cpp
Labels: bug

#49 Add functionality to DataVector and DataFrame.
  src/datasets.cpp
  src/datasets.hpp
  src/test_datasets.cpp
Labels: enhancement

#56 Reorganize code for stopping conditions.
  src/decision_tree.cpp
Labels: bug

#59 Fix potential bug with node linking/unlinking.
  src/tree_node.cpp
Labels: bug

#60 Implement bootstrapping
  src/datasets.cpp
  src/datasets.hpp
  tests/test_datasets.cpp
Labels: enhancement, helpers

#61 Fix missing #include.
  src/decision_tree.cpp
Labels: bug

#57 Implement mostly working version of RF.
  bin/compile.sh
  src/datasets.cpp
  src/datasets.hpp
  src/decision_tree.cpp
  src/decision_tree.hpp
  src/random_forest.cpp
  src/random_forest.hpp
  tests/test_datasets.cpp
  tests/test_random_forest.cpp
Labels: algorithm

#79 RF demo v1
  data/sonar.all-data.numerical.csv
  demo/demo_rf_serial.cpp
  demo/placeholder
  demo/run_v1.png
  demo/run_v2.png
  src/datasets.cpp
Labels: demo

#83 Change multiple defaults
  src/decision_tree.cpp
  src/decision_tree.hpp
  src/random_forest.cpp
  src/random_forest.hpp
Labels: enhancement

#80 Return random seed in SeedGenerator.new_seed()
  src/datasets.cpp
  src/datasets.hpp
  src/decision_tree.cpp
  src/random_forest.cpp
Labels: helpers

#88 Add sample Speed Up plot
  speedup/speedup_plot.py
Labels: demo

#112 OpenMP parallelise mostly everything
  src-openmp/datasets.cpp
  src-openmp/decision_tree.cpp
  src-openmp/random_forest.cpp
Labels: parallelisation

#124 Finalize README report
  README.md
  demo/RF_Parallel_Test.png
  demo/RF_Serial_Demo.png
  demo/RF_Serial_Test.png
  demo/demo_rf_serial
  speedup/SpeedUp_OpenMP.png
  speedup/speedup_plot.py
Labels: documentation

#125 Update relative paths
  README.md
Labels: documentation
